//@version=5
indicator("Heikin-ashi", overlay=false)

///////////////
// Functions //
heikinashi (_o, _h, _l, _c, float _my_close = na) =>
    _hclose = na(_my_close) ? math.avg(_o, _h, _l, _c) : _my_close

    // Day1
    _hopen = math.avg(_o[1], _h[1], _l[1], _c[1])

    // Day2
    if (not na(_hopen[1]))
        _hopen := math.avg(nz(_hopen[1]), nz(_hclose[1]))
    
    [_hopen, high, low, _hclose]

//////////
// Calc //
[hopen, _, _, hclose] = heikinashi(open, high, low, close, ohlc4)
color_body = hclose > hopen ? color.green : color.red
color_wick = color.gray
color_border = color.black

//////////////
// Plotting //
plotcandle(hopen, high, low, hclose, color=color_body, wickcolor=color_wick, bordercolor=color_border)
