//@version=5
indicator("Heikin-ashi", overlay=false)

///////////////
// Functions //
heikinashi (o, h, l, c, latest) =>
    _hclose = latest

    // Day1
    _hopen = math.avg(o[1], h[1], l[1], c[1])

    // Day2
    if (not na(_hopen[1]))
        _hopen := (nz(_hopen[1]) + nz(_hclose[1])) / 2
    
    [_hopen, high, low, _hclose]

//////////
// Calc //
[hopen, _, _, hclose] = heikinashi(open, high, low, close, ohlc4)
color_body = hclose > hopen ? color.green : color.red
color_wick = color.gray
color_border = color.black

//////////////
// Plotting //
plotcandle(hopen, high, low, hclose, color=color_body, wickcolor=color_wick, bordercolor=color_border)
